# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Unit.delete_all
Unit.create!(title: 'Preface')
Unit.create!(title: 'Unit 1: Academics')
Unit.create!(title: 'Unit 2: Social Health and Wellness')
Unit.create!(title: 'Unit 3: Beyond College')
Chapter.delete_all

Chapter.create!(title: 'Welcome To FYE Manual',blurb: 'This is a blurb about the chapter. It can be a few sentences long. Underneath it will be a list of links to supplimental websites', unit_id: 1)
Chapter.create!(title: 'General Things To Know',blurb: 'This is a blurb about the chapter. It can be a few sentences long. Underneath it will be a list of links to supplimental websites', unit_id: 1)
Chapter.create!(title: 'Before The First Day of Class',blurb: 'This is a blurb about the chapter. It can be a few sentences long. Underneath it will be a list of links to supplimental websites', unit_id: 2)
Chapter.create!(title: 'Your Advisor and You',blurb: 'This is a blurb about the chapter. It can be a few sentences long. Underneath it will be a list of links to supplimental websites', unit_id: 2)
Chapter.create!(title: 'FERPA and Student Code of Conduct',blurb: 'This is a blurb about the chapter. It can be a few sentences long. Underneath it will be a list of links to supplimental websites', unit_id: 2)
Chapter.create!(title: 'Grades',blurb: 'This is a blurb about the chapter. It can be a few sentences long. Underneath it will be a list of links to supplimental websites', unit_id: 2)
Chapter.create!(title: 'Learning Resources',blurb: 'This is a blurb about the chapter. It can be a few sentences long. Underneath it will be a list of links to supplimental websites', unit_id: 2)
Chapter.create!(title: 'Time Management',blurb: 'This is a blurb about the chapter. It can be a few sentences long. Underneath it will be a list of links to supplimental websites', unit_id: 2)
Chapter.create!(title: 'Study Skills',blurb: 'This is a blurb about the chapter. It can be a few sentences long. Underneath it will be a list of links to supplimental websites', unit_id: 2)
Chapter.create!(title: 'Financial Aid',blurb: 'This is a blurb about the chapter. It can be a few sentences long. Underneath it will be a list of links to supplimental websites', unit_id: 2)
Chapter.create!(title: 'Choosing a Degree',blurb: 'This is a blurb about the chapter. It can be a few sentences long. Underneath it will be a list of links to supplimental websites', unit_id: 2)
Chapter.create!(title: 'Where Do I go If',blurb: 'This is a blurb about the chapter. It can be a few sentences long. Underneath it will be a list of links to supplimental websites', unit_id: 2)
Chapter.create!(title: 'Research',blurb: 'This is a blurb about the chapter. It can be a few sentences long. Underneath it will be a list of links to supplimental websites', unit_id: 2)
Chapter.create!(title: 'So You Are Not Living in a Dorm',blurb: 'This is a blurb about the chapter. It can be a few sentences long. Underneath it will be a list of links to supplimental websites', unit_id: 3)
Chapter.create!(title: 'Fire and Police',blurb: 'This is a blurb about the chapter. It can be a few sentences long. Underneath it will be a list of links to supplimental websites', unit_id: 3)
Chapter.create!(title: 'I need a Job!',blurb: 'This is a blurb about the chapter. It can be a few sentences long. Underneath it will be a list of links to supplimental websites', unit_id: 3)
Chapter.create!(title: 'The Wood Center',blurb: 'This is a blurb about the chapter. It can be a few sentences long. Underneath it will be a list of links to supplimental websites', unit_id: 3)
Chapter.create!(title: 'Athletics',blurb: 'This is a blurb about the chapter. It can be a few sentences long. Underneath it will be a list of links to supplimental websites', unit_id: 3)
Chapter.create!(title: 'Student Clubs',blurb: 'This is a blurb about the chapter. It can be a few sentences long. Underneath it will be a list of links to supplimental websites', unit_id: 3)
Chapter.create!(title: 'Welcome To the Golden Heart City',blurb: 'This is a blurb about the chapter. It can be a few sentences long. Underneath it will be a list of links to supplimental websites', unit_id: 3)
Chapter.create!(title: 'Do not be an Idiot',blurb: 'This is a blurb about the chapter. It can be a few sentences long. Underneath it will be a list of links to supplimental websites', unit_id: 3)
Chapter.create!(title: 'Student Insurance and the Health Center',blurb: 'This is a blurb about the chapter. It can be a few sentences long. Underneath it will be a list of links to supplimental websites', unit_id: 3)
Chapter.create!(title: 'Counceling',blurb: 'This is a blurb about the chapter. It can be a few sentences long. Underneath it will be a list of links to supplimental websites', unit_id: 3)
Chapter.create!(title: 'Life Skills',blurb: 'This is a blurb about the chapter. It can be a few sentences long. Underneath it will be a list of links to supplimental websites', unit_id: 3)
Chapter.create!(title: 'Internships',blurb: 'This is a blurb about the chapter. It can be a few sentences long. Underneath it will be a list of links to supplimental websites', unit_id: 4)
Chapter.create!(title: 'Resume',blurb: 'This is a blurb about the chapter. It can be a few sentences long. Underneath it will be a list of links to supplimental websites', unit_id: 4)
Chapter.create!(title: 'Interview Skills',blurb: 'This is a blurb about the chapter. It can be a few sentences long. Underneath it will be a list of links to supplimental websites', unit_id: 4)
Chapter.create!(title: 'Elevator Speech',blurb: 'This is a blurb about the chapter. It can be a few sentences long. Underneath it will be a list of links to supplimental websites', unit_id: 4)
Bullet.delete_all
Bullet.create!(bullet: 'This will breakdown how the work book should be used', chapter_id: 1)
Bullet.create!(bullet: 'Should not be read in Chronological Order', chapter_id: 1)
Bullet.create!(bullet: 'Thry to keep this book as a resource beyond the class', chapter_id: 1)
Bullet.create!(bullet: 'Layout Learning Objectives', chapter_id: 1)
Bullet.create!(bullet: 'First Place Students will see the academic calendar', chapter_id: 2)
Bullet.create!(bullet: 'Common Lingo and acronyms that will be consistent in the workbook', chapter_id: 2)
Bullet.create!(bullet: 'The differences in degree types', chapter_id: 2)
Bullet.create!(bullet: 'General Things to know about college and difference from high school', chapter_id: 2)
Bullet.create!(bullet: 'Maslows Hierarchy of Needs', chapter_id: 3)
Bullet.create!(bullet: 'Know your Living Situation', chapter_id: 3)
Bullet.create!(bullet: 'Make sure you are signed up for classes', chapter_id: 3)
Bullet.create!(bullet: 'Know your class schedule and where they are located', chapter_id: 3)
Bullet.create!(bullet: 'Start the semester organized your way', chapter_id: 3)
Bullet.create!(bullet: 'Decentralized model of Advising', chapter_id: 4)
Bullet.create!(bullet: 'What can Sdvisors do for you', chapter_id: 4)
Bullet.create!(bullet: 'Show academic Calendar with when they should meet with an advisor', chapter_id: 4)
Bullet.create!(bullet: 'Example of two and four year plan', chapter_id: 4)
Bullet.create!(bullet: 'class schedule planner', chapter_id: 4)
Bullet.create!(bullet: 'Degree works', chapter_id: 4)
Bullet.create!(bullet: 'What is FERPA', chapter_id: 5)
Bullet.create!(bullet: 'How does FERPA help our the Student', chapter_id: 5)
Bullet.create!(bullet: 'Students rights under FERPA', chapter_id: 5)
Bullet.create!(bullet: 'Practical application', chapter_id: 5)
Bullet.create!(bullet: 'Breaking down the code of conduct', chapter_id: 5)
Bullet.create!(bullet: 'Plagiarism', chapter_id: 5)
Bullet.create!(bullet: 'What does Each grade mean?', chapter_id: 6)
Bullet.create!(bullet: 'NB and I', chapter_id: 6)
Bullet.create!(bullet: 'Academic Probation', chapter_id: 6)
Bullet.create!(bullet: 'The importance of a Syllabus', chapter_id: 6)
Bullet.create!(bullet: 'Breakdown of each learning resource space position', chapter_id: 7)
Bullet.create!(bullet: 'Times, Websites, and Locations', chapter_id: 7)
Bullet.create!(bullet: 'Bullet about time management', chapter_id: 8)
Bullet.create!(bullet: 'Note Taking', chapter_id: 9)
Bullet.create!(bullet: 'How to read a textbook', chapter_id: 9)
Bullet.create!(bullet: 'FAFSA', chapter_id: 10)
Bullet.create!(bullet: 'Scholarships', chapter_id: 10)
Bullet.create!(bullet: 'Eligibility', chapter_id: 10)
Bullet.create!(bullet: 'Academic Plan', chapter_id: 10)
Bullet.create!(bullet: 'Listing types of degrees', chapter_id: 11)
Bullet.create!(bullet: 'Difference between majors and minors', chapter_id: 11)
Bullet.create!(bullet: 'STRONG', chapter_id: 11)
Bullet.create!(bullet: 'Other Ways to get credit', chapter_id: 11)
Bullet.create!(bullet: 'Degree Works', chapter_id: 11)
Bullet.create!(bullet: 'FAQ Style chapter of common questions', chapter_id: 12)
Bullet.create!(bullet: 'URSA', chapter_id: 13)
Bullet.create!(bullet: 'Managing rent', chapter_id: 14)
Bullet.create!(bullet: 'Landlord-tenant relationship', chapter_id: 14)
Bullet.create!(bullet: 'Bullets about police and Fire', chapter_id: 15)
Bullet.create!(bullet: 'Craigslist', chapter_id: 16)
Bullet.create!(bullet: 'Bullet about the wood center', chapter_id: 17)
Bullet.create!(bullet: 'Varsity Sports', chapter_id: 18)
Bullet.create!(bullet: 'Intramural Sports', chapter_id: 18)
Bullet.create!(bullet: 'SRC', chapter_id: 18)
Bullet.create!(bullet: 'Bullets on clubs and organizations', chapter_id: 19)
Bullet.create!(bullet: 'Info about Fairbanks', chapter_id: 20)
Bullet.create!(bullet: 'Bullet point with link', chapter_id: 21)
Bullet.create!(bullet: 'Insurance', chapter_id: 22)
Bullet.create!(bullet: 'health Center', chapter_id: 22)
Bullet.create!(bullet: 'Counseling Bullet point with link', chapter_id: 23)
Bullet.create!(bullet: 'Memory and concentration', chapter_id: 24)
Bullet.create!(bullet: 'Relaxation Techniques', chapter_id: 24)
Bullet.create!(bullet: 'Bullet on Internships', chapter_id: 25)
Bullet.create!(bullet: 'Resume Help', chapter_id: 26)
Bullet.create!(bullet: 'Interview Help', chapter_id: 27)
Bullet.create!(bullet: 'Elevator Speach?', chapter_id: 28)

