# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
#Unit.create!(title: 'Preface')
#Unit.create!(title: 'Unit 1: Academics')
#Unit.create!(title: 'Unit 2: Social Health and Wellness')
#Unit.create!(title: 'Unit 3: Beyond College')
#Chapter.delete_all
Chapter.create!(title: 'Welcome To FYE Manual',unit_id: 1)
Chapter.create!(title: 'General Things To Know',unit_id: 1)
Chapter.create!(title: 'Before The First Day of Class', unit_id: 2)
Chapter.create!(title: 'Your Advisor and You', unit_id: 2)
Chapter.create!(title: 'FERPA and Student Code of Conduct', unit_id: 2)
Chapter.create!(title: 'Grades', unit_id: 2)
Chapter.create!(title: 'Learning Resources', unit_id: 2)
Chapter.create!(title: 'Time Management', unit_id: 2)
Chapter.create!(title: 'Study Skills', unit_id: 2)
Chapter.create!(title: 'Financial Aid', unit_id: 2)
Chapter.create!(title: 'Choosing a Degree', unit_id: 2)
Chapter.create!(title: 'Where Do I go If', unit_id: 2)
Chapter.create!(title: 'Research', unit_id: 2)
Chapter.create!(title: 'So You Are Not Living in a Dorm', unit_id: 3)
Chapter.create!(title: 'Fire and Police', unit_id: 3)
Chapter.create!(title: 'I need a Job!', unit_id: 3)
Chapter.create!(title: 'The Wood Center', unit_id: 3)
Chapter.create!(title: 'Athletics', unit_id: 3)
Chapter.create!(title: 'Student Clubs', unit_id: 3)
Chapter.create!(title: 'Welcome To the Golden Heart City', unit_id: 3)
Chapter.create!(title: 'Do not be an Idiot', unit_id: 3)
Chapter.create!(title: 'Student Insurance and the Health Center', unit_id: 3)
Chapter.create!(title: 'Counceling', unit_id: 3)
Chapter.create!(title: 'Life Skills', unit_id: 3)
Chapter.create!(title: 'Internships', unit_id: 4)
Chapter.create!(title: 'Resume', unit_id: 4)
Chapter.create!(title: 'Interview Skills', unit_id: 4)
Chapter.create!(title: 'Elevator Speech', unit_id: 4)

